export const FETCH_POKEMON_LIST = {
  START: 'FETCH_POKEMON_LIST_START',
  SUCCESS: 'FETCH_POKEMON_LIST_SUCCESS',
  FAILURE: 'FETCH_POKEMON_LIST_FAILURE',
};

export const FETCH_POKEMON_DETAIL = {
  START: 'FETCH_POKEMON_DETAIL_START',
  SUCCESS: 'FETCH_POKEMON_DETAIL_SUCCESS',
  FAILURE: 'FETCH_POKEMON_DETAIL_FAILURE',
};
