export const FETCH_ITEM_LIST = {
  START: 'FETCH_ITEM_LIST_START',
  SUCCESS: 'FETCH_ITEM_LIST_SUCCESS',
  FAILURE: 'FETCH_ITEM_LIST_FAILURE',
};

export const FETCH_ITEM_DETAIL = {
  START: 'FETCH_ITEM_DETAIL_START',
  SUCCESS: 'FETCH_ITEM_DETAIL_SUCCESS',
  FAILURE: 'FETCH_ITEM_DETAIL_FAILURE',
};
