export const FETCH_MOVE_LIST = {
    START: 'FETCH_MOVE_LIST_START',
    SUCCESS: 'FETCH_MOVE_LIST_SUCCESS',
    FAILURE: 'FETCH_MOVE_LIST_FAILURE',
};

export const FETCH_MOVE_DETAIL = {
    START: 'FETCH_MOVE_DETAIL_START',
    SUCCESS: 'FETCH_MOVE_DETAIL_SUCCESS',
    FAILURE: 'FETCH_MOVE_DETAIL_FAILURE',
};
